name: pc-desktop
version: '22-0.3'
type: gadget
build-base: core22
base: core22-desktop
summary: PC gadget for generic devices
description: |
    This gadget enables generic pc devices to work with Ubuntu Core Desktop
confinement: strict
grade: stable
icon: icon.png

parts:
  grub:
    source: .
    build-packages:
      - ubuntu-dev-tools
      - grub-pc-bin
      - grub-common
    plugin: make

